config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  root 'projects#index'
  resources :projects, except: %i[index show] do
    resources :tasks, shallow: true, except: %i[index show] do
      put 'reprioritate', to: 'tasks#reprioritate'
      put 'complete', to: 'tasks#complete'
    end
  end
end

app/models/admin_user.rb
# frozen_string_literal: true

class AdminUser < ApplicationRecord
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  belongs_to :user
  has_many :tasks, -> { order(position: :asc) }, dependent: :destroy
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  belongs_to :project
  acts_as_list scope: :project
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :rememberable, :validatable
  has_many :projects, -> { order(created_at: :desc) }
  has_many :tasks, through: :projects
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  def index
    @projects = current_user.projects
  end

  def new
    @project = ProjectForm.new(Project.new)
  end

  def create
    @project = ProjectForm.new(current_user.projects.new)
    @project.validate(project_params) ? @project.save : render(:new)
  end

  def edit
    @project = current_user.projects.find_by(id: params[:id])
  end

  def update
    @project = ProjectForm.new(current_user.projects.find_by(id: params[:id]))
    @project.validate(project_params) ? @project.save : render(:edit)
  end

  def destroy
    @project = current_user.projects.find_by(id: params[:id])
    @project.destroy
  end

  private

  def project_params
    params.require(:project).permit(:name)
  end
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  def create
    @task = TaskForm.new(current_user.projects.find_by(id: params[:project_id]).tasks.new)
    @task.validate(task_params) ? @task.save : render(:new)
  end

  def reprioritate
    @task = current_user.tasks.find_by(id: params[:task_id])
    ActiveModel::Type::Boolean.new.cast(params[:up]) ? @task.move_higher : @task.move_lower
  end

  def complete
    task = current_user.tasks.find_by(id: params[:task_id])
    task.update(completed: !task.completed)
    render json: '', status: :ok
  end

  def edit
    @task = current_user.tasks.find_by(id: params[:id])
  end

  def update
    @task = TaskForm.new(current_user.tasks.find_by(id: params[:id]))
    @task.validate(task_params) ? @task.save : render(:edit)
  end

  def destroy
    @task = current_user.tasks.find_by(id: params[:id])
    @task.destroy
  end

  private

  def task_params
    params.require(:task).permit(:text, :deadline)
  end
end

app/views/application/_header.html.haml
.header.my-4
  %h1.text-dark.text-center= I18n.t('header')

app/views/application/_sign_out.html.haml
.d-flex.justify-content-end
  %a.btn.btn-secondary{ type: :button, href: destroy_user_session_path, 'data-method': 'delete' }
    %i.bi-box-arrow-right

app/views/layouts/_flash.html.haml
- flash.each do |name, msg|
  .mt-60{id: "flash-#{name}"}
    .alert.alert-dismissible.show{role: "alert", class: "alert-#{name == 'alert' || name == 'error' ? 'warning' : 'success'}"}
      = msg
      %button.close{"aria-label" => "Close", 'data-dismiss' => "alert", type: "button"}
        %span{"aria-hidden" => "true"} &#215;

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %title TaskManager
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag "application", media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = favicon_pack_tag 'unicorn.ico'
  %body{ style: 'background: linear-gradient(0deg, rgba(255,165,2,1) 0%, rgba(180,180,180,1) 75%) center; height: 100vh; background-attachment: fixed;' }
    #flash_div
      = render partial: 'layouts/flash'
    = yield

app/views/projects/_edit.html.haml
= simple_form_for project, method: :patch, remote: true do |f|
  .modal-header
    %h4#myModalLabel.modal-title= I18n.t('edit.project')
  .modal-body
    = f.input :name
  .modal-footer
    = f.button :submit, I18n.t('edit.project')

app/views/projects/_new.html.haml
= simple_form_for project, method: :post, remote: true do |f|
  .modal-header
    %h4#myModalLabel.modal-title= I18n.t('new.project')
  .modal-body
    = f.input :name, required: false
  .modal-footer
    = f.button :submit, I18n.t('new.project')

app/views/projects/_project.html.haml
%table.table-hover.table-light.rounded-bottom.my-5{ id: "project_#{project.id}", style: 'width: 100%' }
  %thead
    %tr
      %th.bg-gradient-primary.text-center
        %i.bi-calendar-event{ style: 'font-size: 1.25rem;' }
      %th.bg-gradient-primary.text-white{style: 'font-size: 18px; width: 82%; '}
        #name.d-flex.justify-content-start
          = project.name
      %th.bg-gradient-primary.d-flex.justify-content-end
        .border-right.px-3
          = link_to edit_project_path(project), { remote: true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window' } do
            %i.bi-pencil.grey{ style: 'font-size: 1.25rem;' }
        .px-3
          = link_to project_path(project), method: :delete, remote: true do
            %i.bi-trash.grey{ style: 'font-size: 1.25rem;' }
    %tr
      %th.text-success.bg-secondary.align-top.pt-1
        %i.visibility_button.bi-plus{ style: 'font-size: 2rem;' }
      %th.bg-secondary.task_form{ colspan: '2' }
        = render partial: 'tasks/inline_form', locals: { project: project, task: Task.new }
  %tbody.tasks
    = render partial: 'tasks/task', collection: project.tasks

app/views/projects/create.js.haml
$("#projects_wrapper").prepend("#{j(render(partial: 'project', locals: {project: @project.model }))}");
$(() => flatpickr($("#project_#{j(@project.id)}").find('.datepicker'), { minDate: 'today' }))
$("#modal-window").modal('hide');

app/views/projects/destroy.js.haml
$("#project_#{j(@project.id)}").remove()

app/views/projects/edit.js.haml
$("#modal-window").find(".modal-content").html("#{j(render(partial: 'edit', locals: { project: @project }))}");
$("#modal-window").modal();

app/views/projects/index.html.haml
= render partial: 'sign_out'
= render partial: 'header'
.container.text-center
  #projects_wrapper
    = render partial: 'project', collection: @projects
  = link_to 'Add TODO List', new_project_path,  { remote: true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'btn btn-primary btn-lg text-light mb-4' }
#modal-window.modal.hide.fade{ "aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: :dialog }
  .modal-dialog{ role: :document }
    .modal-content

app/views/projects/new.js.haml
$("#modal-window").find(".modal-content").html("#{j(render(partial: 'new', locals: { project: @project }))}");
$("#modal-window").modal();

app/views/projects/update.js.haml
$("#project_#{j(@project.id)}").find('#name').html("#{j(@project.name)}");
$("#modal-window").modal('hide');

app/views/tasks/_edit.html.haml
= simple_form_for task, url: task_path(task), method: :put, remote: true do |f|
  .modal-header
    %h4#myModalLabel.modal-title= I18n.t('edit.task')
  .modal-body
    = f.input :text
  .modal-footer
    = f.button :submit, I18n.t('edit.task')

app/views/tasks/_inline_form.html.haml
.pr-2
  = simple_form_for task, url: project_tasks_path(project.id), remote: true do |f|
    .row.justify-content-center
      %div{ style: 'width: 83%' }
        = f.input :text, as: :string, label: false, required: false, placeholder: I18n.t('create.task.text'), input_html: { style: 'width: 100%' }, wrapper_html: { class: 'my-2' }
        = f.input :deadline, as: :string, label: false, required: false, disabled: true, placeholder: I18n.t('create.task.date'), input_html: { class: 'datepicker' }, wrapper_html: { style: 'display: none;' }
      .my-2{ style: 'width: 14%' }
        = f.button :submit, I18n.t('new.task'), style: 'width: 100%'

app/views/tasks/_task.html.haml
%tr.border-top{ id: "task_#{task.id}"}
  %th.border-right.border-top{ style: 'width: 4%' }
    .custom-control.custom-checkbox
      %input#task_completed.form-check-input{ type: 'checkbox', task_id: task.id, checked: task.completed }
  %th.border-right
    .d-flex.justify-content-start.mx-1
      %p.text-muted.fs-6.my-1.text-left
        = task.text
    .d-flex.justify-content-start.mx-1
      %p.text-muted.my-1.deadline
        = task.deadline
  %th
    .d-flex.justify-content-center
      .d-flex.flex-column.px-3.border-right
        = link_to task_reprioritate_path(task, up: 1), method: :put, remote: true do
          %i.bi-chevron-up.dark-grey
        = link_to task_reprioritate_path(task, up: 0), method: :put, remote: true do
          %i.bi-chevron-down.dark-grey
      .d-flex.align-items-center.px-3.border-right
        = link_to edit_task_path(task), { remote: true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window' } do
          %i.bi-pencil.dark-grey
      .d-flex.align-items-center.px-3
        = link_to task_path(task), method: :delete, remote: true do
          %i.bi-trash.dark-grey

app/views/tasks/create.js.haml
$("#project_#{j(@task.project_id)}").find('.tasks').append("#{j(render(partial: 'task', locals: {task: @task.model }))}");
$("#project_#{j(@task.project_id)}").find('.task_form').html("#{j(render(partial: 'inline_form', locals: {project: @task.model.project, task: Task.new }))}");
flatpickr($("#project_#{j(@task.project_id)}").find('.datepicker'), { minDate: 'today' });

app/views/tasks/destroy.js.haml
$("#task_#{j(@task.id)}").remove()

app/views/tasks/edit.js.haml
$("#modal-window").find(".modal-content").html("#{j(render(partial: 'edit', locals: { task: @task }))}");
$("#modal-window").modal();

app/views/tasks/new.js.haml
$("#project_#{j(@task.project_id)}").find('.task_form').html("#{j(render(partial: 'inline_form', locals: {project: @task.model.project, task: @task }))}");
flatpickr($("#project_#{j(@task.project_id)}").find('.datepicker'), { minDate: 'today' })
- if params.dig(:task, :deadline)
    deadline = $("#project_#{j(@task.project_id)}").find('.task_deadline')
    deadline_input = deadline.find('#task_deadline')
    deadline.show()
    deadline_input.removeAttr('disabled')
    deadline_input.removeAttr('readonly')

app/views/tasks/reprioritate.js.haml
$("#project_#{j(@task.project_id)} > .tasks").html("#{j(render(partial: 'task', collection: @task.project.tasks))}");

app/views/tasks/update.js.haml
$("#task_#{j(@task.id)}").replaceWith("#{j(render(partial: 'task', locals: {task: @task.model }))}");
$("#modal-window").modal('hide');